#!/usr/bin/env python
"""
A script that takes a set of directories and file numbers and cleans data appropriately.

The default subarr is 256, in order for full compatability with default IDL code.
"""

import sys
import numpy as np
# This includes an AO Instrument called "aoinst"
import pypoise
import nirc2
import pdb
import os

#Create a pypoise instance with a nirc2 AO instrument
pp = pypoise.PYPOISE(nirc2.NIRC2())

if sys.argv[1] == 'd':
    do_we_dither = True
else:
    do_we_dither = False

pp.aoinst.rdir = sys.argv[2] 
pp.aoinst.ddir = sys.argv[3] 
pp.aoinst.cdir = sys.argv[4] 
fstart = int(sys.argv[5])
nfs    = int(sys.argv[6])

#run_make_ftpix ~/tel/nirc2/analysis/ScoBin15a/ ~/data/nirc2/150623/ 194 8

extn = '.fits'

files = [('n{0:04d}' + extn).format(i + fstart) for i in range(nfs)]

if (not os.path.exists(pp.aoinst.rdir + "FTPIX_COMPLETE")):
    (ftpix, fmask, ptok, pmask) = pp.pupil_sampling(files,dither=do_we_dither)

with open(pp.aoinst.rdir + "FTPIX_COMPLETE","w+") as f:
    f.close()