#!/usr/bin/env python
"""
A script that takes a set of directories and file numbers and cleans data appropriately.

The default subarr is 256, in order for full compatability with default IDL code.
"""

from __future__ import print_function, division
import sys
import numpy as np
# This includes an AO Instrument called "aoinst"
import pypoise
import nirc2, conica
import pdb
import os
import astropy.io.fits as pyfits
if len(sys.argv)==1:
    print("Useage: run_make_ftpix [s|m|d] rdir ddir fstart nfs [instname]")
    sys.exit()

if not sys.argv[len(sys.argv)-1][0] in '0123456789':
    instname = sys.argv[len(sys.argv)-1]
else:
    instname = 'NIRC2'
if instname=='NIRC2':
    #Create a pypoise instance with a nirc2 AO instrument
    pp = pypoise.PYPOISE(nirc2.NIRC2())
elif instname=='NACO':
    #Create a pypoise instance with a conica AO instrument
    pp = pypoise.PYPOISE(conica.CONICA())
dither_string = sys.argv[1]

if (dither_string.find('s') >= 0):
    destripe=False
else:
    destripe=True
if (dither_string.find('m') >= 0):
    manual_click=True
else:
    manual_click=False
if (dither_string.find('d') >= 0):
    do_we_dither=True
else:
    do_we_dither=False
    
pp.aoinst.rdir = sys.argv[2] + '/' 
pp.aoinst.ddir = sys.argv[3] + '/' 
fstart = sys.argv[4]
nfs    = int(sys.argv[5])

#run_make_ftpix n ~/tel/nirc2/analysis/ScoBin15a/ ~/data/nirc2/150623/ ./ 194 8
#run_make_ftpix n ./ /Users/mireland/data/nirc2/141130/ 89 9

extn = '.fits'

if instname=='NACO':
	files = []
	for j in os.listdir(pp.aoinst.ddir):
		if 'fit' in j:
			hdr = pyfits.getheader(pp.aoinst.ddir+'/'+j)
			if hdr['ESO TPL START']==fstart:
				files.append(pp.aoinst.ddir+'/'+j)
elif instname=='NIRC2':
	fstart = int(fstart)
	files = [('n{0:04d}' + extn).format(i + fstart) for i in range(nfs)]
print(files)
if (not os.path.exists(pp.aoinst.rdir + "FTPIX_COMPLETE")):
    (ftpix, fmask, ptok, pmask) = pp.pupil_sampling(files,dither=do_we_dither,subarr=192)

with open(pp.aoinst.rdir + "FTPIX_COMPLETE","w+") as f:
    f.close()
