#!/usr/bin/env python
"""
A script that takes a set of directories and file numbers and makes python calibrations.

It is important to note that run_csv has to be run first.

Note that flats are not always made... extra logical links could be useful.
"""

from __future__ import print_function, division

import sys
import numpy as np
# This includes an AO Instrument called "aoinst"
import pypoise
import nirc2, conica
import pdb
import os

if len(sys.argv) < 3:
    print("Useage: run_calibration REDUCTION_DIR DATA_DIR [INSTRUMENT]")
    sys.exit()

if len(sys.argv)>3:
    instname = sys.argv[3]
else:
    instname = 'NIRC2'
if instname=='NIRC2':
    #Create a pypoise instance with a nirc2 AO instrument
    pp = pypoise.PYPOISE(nirc2.NIRC2())"""
elif instname=='NACO':
    #Create a pypoise instance with a conica AO instrument
    pp = pypoise.PYPOISE(conica.CONICA())

pp.aoinst.rdir = sys.argv[1] 
pp.aoinst.ddir = sys.argv[2] 
if pp.aoinst.rdir[-1] != '/':
    pp.aoinst.rdir += '/'
if pp.aoinst.ddir[-1] != '/':
    pp.aoinst.ddir += '/'


#pp.aoinst.rdir = '/Users/mireland/tel/nirc2/analysis/ScoBin15a/'
#pp.aoinst.ddir = '/Users/mireland/data/nirc2/150623/'

pp.aoinst.read_summary_csv()

if (not os.path.exists(pp.aoinst.rdir + "CAL_COMPLETE")):
    pp.aoinst.make_all_darks()
    pp.aoinst.make_all_flats()

with open(pp.aoinst.rdir + "CAL_COMPLETE","w+") as f:
    f.close()
