#!/usr/bin/env python

#import pyximport; pyximport.install()
from __future__ import print_function
import popCSV
import time#, jpb
import os,sys

print('Program started at time:')
print(time.asctime( time.localtime(time.time()) ))

path = './'#jpb.ask('Which directory to run this code?','./') # path to root of directory to walk through, relative to location of script
outfile = path + "datainfo.csv" # the output file to write to
textfile = path + "blockinfo.txt" # the output file to write to
if len(sys.argv)>1:
    instname = sys.argv[1]
else:
    instname = 'NIRC2'
if instname=='NACO':
    filter = 'ESO INS OPTI6 ID'
    inttime = 'EXPTIME'
    alt = 'ESO TEL ALT'
elif instname=='NIRC2':
    filter = 'FILTER'
    inttime = 'ITIME'
    alt = 'EL'
keys = [filter, \
        "EFFWAVE", \
        "OBJECT", \
        "TARGNAME", \
        "CAMNAME", \
        "IMAGETYP", \
        "SHRNAME", \
        "SLITNAME",\
        "COADDS", \
        inttime, \
        "DATE-OBS", \
        "MJD-OBS", \
        "UTC", \
        alt, \
        "RA", \
        "DEC", \
        "NAXIS1", \
        "NAXIS2", \
        "PIXSCALE", \
        "SLITNAME", \
        "FWINUM", \
        "FWONUM"]
blockkeys = [filter,"OBJECT","TARGNAME","COADDS",inttime,"NAXIS1","NAXIS2","SAMPMODE", "MULTISAM"]     

# The headers for analysis done on the files
# MULTISAM is 1 if SAMPMODE is 2, else write value in header
# PEAKPIX is one operation, but returns 2 values, needs two columns
# SATURATED be sure to set the threshold value for level before saturated
operations = ["MULTISAM", \
              "PEAKPIX(X)", \
              "PEAKPIX(Y)", \
              "PEAK_VALUE", \
              "MEDIAN_VALUE", \
              "SATURATED" \
             ]

# try to be fancy writing the column headers
# Directory and Filename are always going to be the first two columns for the output
colheads = ["DIRECTORY", \
            "FILENAME" \
           ]

colheads=colheads+keys+operations

########################
# Begin main part of the script
########################

popCSV.popCSV(keys,operations,colheads,path,outfile,textfile=textfile,blockkeys=blockkeys,total_int_keys=["COADDS",inttime], instname=instname)


print('CSV generation finished at time:')
print(time.asctime( time.localtime(time.time()) ))
