#!/usr/bin/env python
"""
A script that takes a set of directories and file numbers and makes python calibrations.

Note that flats are not always made... extra logical links could be useful.
"""

import sys
import numpy as np
# This includes an AO Instrument called "aoinst"
import pypoise
import nirc2
import pdb
import os

#Create a pypoise instance with a nirc2 AO instrument
pp = pypoise.PYPOISE(nirc2.NIRC2())

pp.aoinst.rdir = sys.argv[1] 
pp.aoinst.ddir = sys.argv[2] 

#pp.aoinst.rdir = '/Users/mireland/tel/nirc2/analysis/ScoBin15a/'
#pp.aoinst.ddir = '/Users/mireland/data/nirc2/150623/'

pp.aoinst.read_summary_csv()

if (not os.path.exists(pp.aoinst.rdir + "CAL_COMPLETE")):
    pp.aoinst.make_all_darks()
    pp.aoinst.make_all_flats()

with open(pp.aoinst.rdir + "CAL_COMPLETE","w+") as f:
    f.close()